### ISSUE TITLE
sdiv/udiv instruction

### ISSUE THREAD

**Issue by parrotgeek1** [Unlegacy-Android/android_kernel_samsung_tuna#3]
hi

omap4 doesn't support integer divide instructions used in some gapps (swipe prebuilt / drm)

there is a patch from Droid 4 kernel to emulate them

https://github.com/CyanogenMod/android_kernel_motorola_omap4-common/commit/8b554c0f5ea7ade4dfd2cbb56d3b807f49f34da6
https://github.com/CyanogenMod/android_kernel_motorola_omap4-common/commit/dd415d94e89e6ae8df322dec861f210f51375502

**Comment by MWisBest** [comment]
We already have these in this kernel.
